Using filter() and lambda, extract even numbers from a given list.
Input Format:
 Integers separated by space.
Output Format:
 List of even integers.
Example:
Input: 5 6 7 8 9 10  
Output: [6, 8, 10]


In [ ]:
get_input = input().strip()
convert_number = map(int, get_input.split())
convert_list = list(convert_number)

evenNumber = list( filter(lambda x: x % 2 == 0, convert_list))

print(evenNumber)

Write a function safe_divide(a,b) that performs a/b and handles division by zero using try–except.
 Print "Division by zero" if b = 0.
Input Format:
 Two integers a b.
Output Format:
 Result or error message.
Example:
Input: 10 0  
Output: Division by zero


In [2]:
def safe_divide(a, b):
  try:
    result = a/b
    print(result)
  except ZeroDivisionError:
    print("Division by zero")

a, b = map(int, input().split())

safe_divide(a, b)

ValueError: not enough values to unpack (expected 2, got 0)

Create a base class Shape with a method area() that returns 0.
 Create subclasses:
Rectangle(w,h) → area = w × h


Circle(r) → area = π × r²


Read shape type and parameters, then print area (rounded to 2 decimals).
Input Format 1:
Rectangle 5 10

Output Format 1:
Area: 50.00


Input Format 2:
Circle 7

Output Format 2:
Area: 153.94


In [ ]:
import math
## base Class
class Shape:
  def area(self):
    return 0

## sub class for reactange
class Rectangle(Shape):
  def __init__(self, w, h):
    self.w = w
    self.h = h
  def area(self):
    return self.w * self.h

## Sub Class for Circle
class Circle(Shape):

  def __init__(self, r):
    self.r = r

  def area(self):
    return  math.pi * (self.r ** 2)

## Rectangle object create
rect = Rectangle(5, 10)
area = rect.area()
print(f"Area: {area: .2f}")

## Cricle object Create
circle = Circle(7)

circle_area = circle.area()
print(f"Area: {circle_area: .2f}")


Find and print the longest word in a given sentence (if tie, print first one).
Input Format:
 One line string
Output Format:
 Longest word
Example:
Input: Python programming is enjoyable
Output: programming


In [ ]:
def longest_word(sentance):
  # sentance convert to list
   word = sentance.split()
   ## use max  function or method  long word  count
   long_word = max(word, key=len)
   return long_word


get_input_string = input().strip()

result = longest_word(get_input_string)

print(result)


A number is called strong if the sum of the factorial of its digits equals the number itself.
 Example: 145 = 1! + 4! + 5!
Input Format:
 Single integer
Output Format:
 "Strong Number" or "Not Strong Number"
Example:
Input: 145
Output: Strong Number


In [ ]:
import math
def strong_number (number):
    copy_orginal_number = number
    fac_sum = 0;

    ## looping

    while number > 0:
        # get last digit
        digit = number % 10
        # add factorial of digit
        fac_sum += math.factorial(digit)
        number //= 10

    # check the strong number
    if fac_sum == copy_orginal_number:
        print("Strong Number")
    else :
        print("Not Strong Number")

number = int(input().strip())

strong_number(number)



In [9]:
sum = 1;
for i in range(1,145):
    sum += i


print(sum%10)

print(sum)


1
10441


In [11]:
import numpy as np 

arr = np.array([1,2,3])
print(arr.ndim)

# print(np.eye(3))
# print(np.eye(3))
# print(np.eye(3))
print(np.linspace(0,10,5))
print(np.full((2,2), np.inf))

arr = np.array([[10,20,30],[40,50,60]])

print(arr[:,1])

print(np.random.rand(2,3) )

arr = np.array([1,2,3,4,5])

arr[1:4] = 0

print(arr)

1
[ 0.   2.5  5.   7.5 10. ]
[[inf inf]
 [inf inf]]
[20 50]
[[0.77614528 0.8613279  0.40602115]
 [0.22913679 0.94382889 0.72516328]]
[1 0 0 0 5]


In [ ]:
## np.linspace(start, end(included), kayta value nibo)
import numpy as np
arr = np.linspace(1, 10, 20)

print(arr)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [11]:
# np.logspace(start, end(included), koyta value nibo)

arr = np.logspace(0, 4, 5)
print(arr)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]


In [15]:
## diagonal matrix 

diagonal_matrix = np.diag([2,3,4,9])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 9]]
(4, 4)


In [25]:
# identity matrix 

identity_matrix = np.eye(3)

# print(identity_matrix)

## modify identity matrix 
# identity_matrix_modify = np.eye(4, 5)
identity_matrix_modify = np.eye(4, 5 ,2)
print(identity_matrix_modify)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [ ]:
## indexing 
arr = np.array([3,4,5,6,7,8,9,10])
print(arr[2])
## slicing 
# print(arr[1:6:2])
arr1 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

# print(arr1[0][2])
# 2d array slicing  arr[row_start: row_end:step, column_start: column_end:step]

print(arr1[0:1, ])

# print(arr1[::, 1:4])



5
[[1 2 3 4 5]]
[[2 3 4]
 [7 8 9]]


In [41]:
## Advancing indexing 

lst = np.array([10,30, 20, 40, 50])

values = lst[[2,3, 1]]
# print(values)

d2array = np.array([
    [3,4,5,6,7,8,9],
    [2,3,4,5,6,7,9]
])

for i in np.nditer(d2array):
    print(i)
# print(d2array[[0,1],[2,4]])

3
4
5
6
7
8
9
2
3
4
5
6
7
9
