## Slicing Arrays
#### Slicing in python means takeing element form one given index to another given index 
we pass slice instead of index like this [start:end]
we can also define the step , like this [start_index:end_index:step]
if we don't pass start its considered 0
if we don't pass end its considered length of array in that dimension 
if we don't pass step its considered 1

### `note : the result included the start index, but excludes the end index`

In [7]:
import numpy as np
arr = np.array([2,3,4,5,6,7,8])

## beginning 
# print(arr[:4])
## ending 
# print(arr[3:])
## Negative Slicing 
print(arr[-4:-1])

[5 6 7]


In [ ]:
## Step 
## use the Step value to determine the step of the slicing 

import numpy as np
arr = np.array([2,3,4,5,6,7,8,9])

print(arr[1:5:2])
## return every element from the array  where even numbers
print(arr[::2])

[3 5]
[2 4 6 8]


## Slicing 2-D arrays 

In [10]:
import numpy as np 
arr = np.array(
    [
        [2,3,4,5, 6,7,8,9,10],
        [12,13,14,15,16,17,18,19,20]
    ]
)

print(arr[1, 1:5])

[13 14 15 16]


In [11]:
## From both elements return index 2

import numpy as np
arr = np.array(
    [
        [1,2,3,4,5], [6,7,8,9,10]
    ]
)

print(arr[0:2, 2])

[3 8]


In [12]:
## From both elements, Slice index 1 to index 4 (not included) this will return a 2-D array
import numpy as np
arr = np.array(
    [
        [1,2,3,4,5],
        [6,7,8,9,10]
    ]
)

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
