## NumPy Array Reshaping 

Reshaping arrays 
reshaping means changing the shape of an array
the shape of an array is the number of elements in each dimension 

By reshaping we can add or remove dimension or change number of elements in each dimension 

Reshape from 1-D To 2-D 
Convert  1-D array with 2-D array 

the outermost dimension 

In [3]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

new_arr = arr.reshape(3,4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
## Reshape form 1-D to 3-D array 

import numpy as np 
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

new1_arr = arr1.reshape(3,4)
print(new1_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
