In [1]:
## Transpose matrix 
import numpy as np

mat = np.array([
    [10, 20, 30, 40, 50],
    [30,40,50, 60,70]
])
## convert to transport matrix

transporse = mat.T

print(transporse)



[[10 30]
 [20 40]
 [30 50]
 [40 60]
 [50 70]]


In [4]:
## Array split 

arr = np.random.randint(2,15, size=(15,))
print(arr)
## array split 
arr_split = np.array_split(arr, 4)
print(arr_split )

[ 7  4  4  8  2  5 10  3 14  4 11  9  3  2 13]
[array([7, 4, 4, 8], dtype=int32), array([ 2,  5, 10,  3], dtype=int32), array([14,  4, 11,  9], dtype=int32), array([ 3,  2, 13], dtype=int32)]


## Arithmetic operator and mathematical functions 

In [ ]:
x = np.array([10,20,30])
y = np.array([30, 40, 50])

add = x+y;
print(add)
## minus 
minis = x-y;
print(minis)
## multiplication 
mul = x*y;
print(mul)



[40 60 80]
[-20 -20 -20]
[ 300  800 1500]


In [ ]:
## Mathematical function 


## 

In [8]:
## Broad casting 
x = np.array([10, 8, 16, 100])

squear = x **2;

print(squear)

[  100    64   256 10000]


In [11]:
maxtrix = np.array([
    [10, 20, 30],
    [30, 40, 50]
])
vector = np.array([3,4,5])
addition = maxtrix + 2;
print(addition)

addVector_and_maxtrix = maxtrix+vector
print(addVector_and_maxtrix)

[[12 22 32]
 [32 42 52]]
[[13 24 35]
 [33 44 55]]


In [20]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print(b.shape)

print(np.sin(np.pi/2))

c = np.array([1,2,3])
d = np.array([4,5,6])
print(c+d)

print(np.sort(np.array([3,1,2])))

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A*B)


(2, 3)
1.0
[5 7 9]
[1 2 3]
[[ 5 12]
 [21 32]]
