## Create a NumPy ndarray object
numPy is used to work with arrays.  The array object in NumPy is called ndarray
We can create a NumPy ndarray object using the array() function

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
# type of array
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## `type(): This built-in Python function tells us the type of the object passed to it . Like in above code it show that  arr is  numpy.ndarray type `

In [3]:
import numpy as np 
## use a tuple to crete a numpy array
arr = np.array((2,3,4,5,6))
print(arr)

[2 3 4 5 6]


## Dimensions in Array
A dimension in arrays is one level of array depth (nested array)

### nested array : are arrays that have arrays as their elements

## 0-D Arrays 
0-D arrays or Scalars Are the elements in array. Each value in array is a 0-D array

In [4]:
## Create a 0-D Array values 42
import numpy as np 
arr = np.array(42)
print(arr)

42


## 1-D arrays 
an array that has 0-D arrays as its elements is called uni-dimensional or 1-D array

These are the most Common and basic Array


In [5]:
## Create a 1-D array containing the values 1,2,3,4,5
import numpy as np 

arr = np.array([2,3,4,5,6])
print(arr)

[2 3 4 5 6]


## 2-D arrays 
An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2d order tensors.

* NumPy has a  whole sub module dedicated towards matrix operations called `numpy.mat` *

In [6]:
## Create a 2-D array containing two arrays with the values 

import numpy as np
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
## Ann Array that has 2-D  arrays (matrixes) as its elements is called 3-D array
## These are often used to represent a 3rd order tensor 
import numpy as np
arr = np.array([[
    [1,2,3],
     [4,5,6]
],
[
    [7,8,9],
    [10,11,12]
]    
])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Check Number of Dimensions 
NumPy Arrays Provides the `ndim` attribute that return an integer that tells us how many dimensions the array have 

In [12]:
import numpy as np
zero = np.array(42)
one_dim = np.array([1,2,3,4,5])
two_dim = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

three_dim = np.array(
    [
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ],
        [
            [10, 11,12],
            [13,14,15],
            [16,17,18]
        ]

    ]
)

print('zero', zero.ndim)
print('one dimension', one_dim.ndim)
print('two dim', two_dim)
print('three  dim', three_dim.ndim)

zero 0
one dimension 1
two dim [[1 2 3 4]
 [5 6 7 8]]
three  dim 3


## Higher Dimensional Array 
An Array can have any number of dimension 

When the array is created you can defined the number of dimensions by using the `ndim` argument

In [16]:
import numpy as np 

arr = np.array([1,2,3,4], ndmin=4)
print(arr)
print(arr.ndim)

[[[[1 2 3 4]]]]
4
