In [2]:
import torch as tc
import torch.nn as nn

tensor = tc.Tensor([[1, 2], [3, 4]])
print("Original Tensor:")
print(tensor)

Original Tensor:
tensor([[1., 2.],
        [3., 4.]])


In [3]:
tesnor_1d = tc.Tensor([1, 2, 3, 4, 5])
print("1D Tensor:")
print(tesnor_1d)
print("Shape of 1D Tensor:", tesnor_1d.shape)
print("Reshaped to 5x1 Tensor:")
reshaped_tensor = tesnor_1d.view(5, 1)
print(reshaped_tensor)
print("Shape of Reshaped Tensor:", reshaped_tensor.shape)

1D Tensor:
tensor([1., 2., 3., 4., 5.])
Shape of 1D Tensor: torch.Size([5])
Reshaped to 5x1 Tensor:
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])
Shape of Reshaped Tensor: torch.Size([5, 1])


In [4]:
tensor_2d = tc.Tensor([[1, 2, 3], [4, 5, 6]])
print("2D Tensor:")
print(tensor_2d)
print("Shape of 2D Tensor:", tensor_2d.shape)
print("Reshaped to 3x2 Tensor:")
reshaped_tensor_2d = tensor_2d.view(3, 2)
print(reshaped_tensor_2d)
print("Shape of Reshaped 2D Tensor:", reshaped_tensor_2d.shape)
print("Transpose of Reshaped 2D Tensor:")
transposed_tensor = reshaped_tensor_2d.t()
print(transposed_tensor)
print("Shape of Transposed Tensor:", transposed_tensor.shape)
print("Element at (0,1) in Original Tensor:", tensor[0, 1].item())
print("Element at (2,1) in Reshaped 2D Tensor:", reshaped_tensor_2d[2, 1].item())
print("Element at (1,0) in Transposed Tensor:", transposed_tensor[1, 0].item()) 
print("Element at (4) in 1D Tensor:", tesnor_1d[4].item())

    

2D Tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Shape of 2D Tensor: torch.Size([2, 3])
Reshaped to 3x2 Tensor:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Shape of Reshaped 2D Tensor: torch.Size([3, 2])
Transpose of Reshaped 2D Tensor:
tensor([[1., 3., 5.],
        [2., 4., 6.]])
Shape of Transposed Tensor: torch.Size([2, 3])
Element at (0,1) in Original Tensor: 2.0
Element at (2,1) in Reshaped 2D Tensor: 6.0
Element at (1,0) in Transposed Tensor: 2.0
Element at (4) in 1D Tensor: 5.0


In [6]:
## Tensor Operations in pyTorch
a = tc.Tensor([[1, 2], [3, 4]])
b = tc.Tensor([[5, 6], [7, 8]])
print("Tensor A:")
print(a)
print("Tensor B:")
print(b)
print("Addition of A and B:")
c = a + b
print(c)
print("Subtraction of B from A:")   
d = a - b
print(d)
print("Element-wise Multiplication of A and B:")
e = a * b
print(e)
print("Element-wise Division of A by B:")
f = a / b
print(f)
print("Matrix Multiplication of A and B:")
g = tc.mm(a, b)
print(g)
print("Exponentiation of A (A squared):")
h = a ** 2
print(h)
print("Square Root of B:")
i = tc.sqrt(b)
print(i)
print("Sum of all elements in A:")
j = tc.sum(a)
print(j)
print("Mean of all elements in B:")
k = tc.mean(b)
print(k)
print("Maximum value in A:")
l = tc.max(a)
print(l)
print("Minimum value in B:")
m = tc.min(b)
print(m)
print("Standard Deviation of elements in A:")
n = tc.std(a)
print(n)
print("Variance of elements in B:")
o = tc.var(b)
print(o)
print("Reshaping A to 4x1 Tensor:")
p = a.view(4, 1)
print(p)
print("Flattening B to 1D Tensor:")
q = b.view(-1)
print(q)
print("Transposing A:")
r = a.t()
print(r)
print("Slicing first row of B:")
s = b[0, :]
print(s)
print("Slicing second column of A:")
t = a[:, 1]
print(t)
print("Concatenating A and B along rows:")
u = tc.cat((a, b), dim=0)
print(u)
print("Concatenating A and B along columns:")
v = tc.cat((a, b), dim=1)
print(v)
print("Stacking A and B along a new dimension:")
w = tc.stack((a, b), dim=0)
print(w)
print("Creating a Tensor of zeros with shape 2x3:")
x = tc.zeros((2, 3))
print(x)
print("Creating a Tensor of ones with shape 3x2:")
y = tc.ones((3, 2))
print(y)
print("Creating a Tensor with random values of shape 2x2:")
z = tc.rand((2, 2))
print(z)
print("Creating a Tensor with values from a normal distribution (mean=0, std=1) of shape 2x2:")
aa = tc.randn((2, 2))
print(aa)
print("Creating a Tensor with values from a uniform distribution [0,1) of shape 2x2:")
bb = tc.rand((2, 2))
print(bb)
print("Creating a Tensor with values from a uniform distribution [a,b) of shape 2x2 (a=5, b=10):")
cc = tc.empty((2, 2)).uniform_(5, 10)
print(cc)
print("Creating a Tensor with values from a normal distribution (mean=mu, std=sigma) of shape 2x2 (mu=3, sigma=0.5):")
dd = tc.empty((2, 2)).normal_(3, 0.5)
print(dd)
print("Creating a Tensor with values from a binomial distribution (n=10, p=0.5) of shape 2x2:")
ee = tc.empty((2, 2)).bernoulli_(0.5) * 10
print(ee)
print("Creating a Tensor with values from a Poisson distribution (lambda=4) of shape 2x2:")
ff = tc.poisson(tc.full((2, 2), 4.0))
print(ff)



Tensor A:
tensor([[1., 2.],
        [3., 4.]])
Tensor B:
tensor([[5., 6.],
        [7., 8.]])
Addition of A and B:
tensor([[ 6.,  8.],
        [10., 12.]])
Subtraction of B from A:
tensor([[-4., -4.],
        [-4., -4.]])
Element-wise Multiplication of A and B:
tensor([[ 5., 12.],
        [21., 32.]])
Element-wise Division of A by B:
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
Matrix Multiplication of A and B:
tensor([[19., 22.],
        [43., 50.]])
Exponentiation of A (A squared):
tensor([[ 1.,  4.],
        [ 9., 16.]])
Square Root of B:
tensor([[2.2361, 2.4495],
        [2.6458, 2.8284]])
Sum of all elements in A:
tensor(10.)
Mean of all elements in B:
tensor(6.5000)
Maximum value in A:
tensor(4.)
Minimum value in B:
tensor(5.)
Standard Deviation of elements in A:
tensor(1.2910)
Variance of elements in B:
tensor(1.6667)
Reshaping A to 4x1 Tensor:
tensor([[1.],
        [2.],
        [3.],
        [4.]])
Flattening B to 1D Tensor:
tensor([5., 6., 7., 8.])
Transposing A:
tens