In [1]:
# import NumPy
# onces Numpy is install, import it in your application by adding the import keyword 

import numpy

arr = numpy.array([2,3,5,6,7,8])

print(arr)

[2 3 5 6 7 8]


In [3]:
# NumPy as np
# NumPy is usually imported under the np alias.

# alias: In Python alias are an alternate name for referring to the same thing.

# Create an alias with the as keyword while importing:

import numpy as np

arr = np.array([5,6,7,8,1,23,4])

print(arr)

## cheeking Numpy version 

print(np.__version__)

[ 5  6  7  8  1 23  4]
2.3.3


In [6]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])


7


Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [10]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [11]:
# Access 3-D Arrays
# To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6
